### PR TITLE
Fix Numeric Map Key Traversal bug

### LINKED ISSUE #2: Cursor parsing maps with integer values fails
If you have a map with a numeric key, resolve/glob think that the datastructure must be an array, rather than a map, and it fails to find your key. Or put another way, when processing a map, resolve/glob do not look at keys that are numeric values, or stringified forms of numeric values.

May only be an issue when processing map[string]interface{} and map[interface{}]interface{} works?

### PR DESCRIPTION
**Pull request by jhunt**
This fixes #2 by considering the string value of each found key in a
`map[interface{}] interface{}`, instead of hoping that there is an exact
string match (type included) with the cursor node we are currently
examining.  This situation generally only occurs with YAML documents,
since the YAML spec doesn't force string keys the way JSON does.

### CODE REVIEW

**Comment by jhunt** [comment]
@geofffranks you want to take a look at this and see what you think?  There's tons of duplication (but then again, there was tons of duplication _before_ I started too...

**Comment by geofffranks** [comment]
I'm confused why this is only YAML, since I was experiencing the bug with JSON, unless the case switch was perferring `map[interface{}]interface{}` over `map[string]interface{}`.

**Comment by jhunt** [comment]
YAML allows non-string and composite keys. JSON does not.


--
http://jameshunt.us
@iamjameshunt


-------- Original message --------

**Comment by geofffranks** [comment]
Tested with esuf, I'm still getting issues. Maybe unrelated to this, since it's using JSON, which shouldn't have suffered from the bug?

**Comment by geofffranks** [comment]
Yes. Esuf's issues are unrelated.

**Pull request merged**
